// AUTO-GENERATED by extract-kaikki-words.py
// Category : Time & Frequency
// Words    : 30 | Examples: 30 | Pronunciation: 30
// Source   : Kaikki_Enriched/*_enriched_categorized/
// Review before merging into src/data/slovak-words.ts

import type { WordCategory } from "@/types/learning";

export const CALENDAR_AND_DATES: WordCategory = {
  icon: "⏰",
  title: "Time & Frequency",
  description: "Time expressions and frequency words",
  level: "beginner",
  words: [
      { id: "w-calendar-dat-januar", english: "January", slovak: "január", type: "noun", gender: "masculine", pronunciation: "ja-nu-ár", english_example: "My birthday is in January.", slovak_example: "Moje narodeniny sú v januári." },
      { id: "w-calendar-dat-februar", english: "February", slovak: "február", type: "noun", gender: "masculine", pronunciation: "feb-ru-ár", english_example: "February is short.", slovak_example: "Február je krátky." },
      { id: "w-calendar-dat-marec", english: "March", slovak: "marec", type: "noun", gender: "masculine", pronunciation: "ma-rec", english_example: "Spring starts in March.", slovak_example: "Jar začína v marci." },
      { id: "w-calendar-dat-april", english: "April", slovak: "apríl", type: "noun", gender: "masculine", pronunciation: "ap-ríl", english_example: "It often rains in April.", slovak_example: "V apríli často prší." },
      { id: "w-calendar-dat-maj", english: "May", slovak: "máj", type: "noun", gender: "masculine", pronunciation: "máj", english_example: "May is beautiful.", slovak_example: "Máj je krásny." },
      { id: "w-calendar-dat-jun", english: "June", slovak: "jún", type: "noun", gender: "masculine", pronunciation: "jún", english_example: "School ends in June.", slovak_example: "Škola končí v júni." },
      { id: "w-calendar-dat-jul", english: "July", slovak: "júl", type: "noun", gender: "masculine", pronunciation: "júl", english_example: "July is hot.", slovak_example: "Júl je horúci." },
      { id: "w-calendar-dat-august", english: "August", slovak: "august", type: "noun", gender: "masculine", pronunciation: "au-gust", english_example: "We vacation in August.", slovak_example: "Dovolenujeme si v auguste." },
      { id: "w-calendar-dat-september", english: "September", slovak: "september", type: "noun", gender: "masculine", pronunciation: "sep-tem-ber", english_example: "School starts in September.", slovak_example: "Škola začína v septembri." },
      { id: "w-calendar-dat-oktober", english: "October", slovak: "október", type: "noun", gender: "masculine", pronunciation: "ok-tó-ber", english_example: "Leaves fall in October.", slovak_example: "Listy padajú v októbri." },
      { id: "w-calendar-dat-november", english: "November", slovak: "november", type: "noun", gender: "masculine", pronunciation: "no-vem-ber", english_example: "November is grey.", slovak_example: "November je sivý." },
      { id: "w-calendar-dat-december", english: "December", slovak: "december", type: "noun", gender: "masculine", pronunciation: "de-cem-ber", english_example: "Christmas is in December.", slovak_example: "Vianoce sú v decembri." },
      { id: "w-calendar-dat-jar", english: "spring", slovak: "jar", type: "noun", gender: "feminine", pronunciation: "jar", english_example: "I love spring.", slovak_example: "Mám rada jar." },
      { id: "w-calendar-dat-leto", english: "summer", slovak: "leto", type: "noun", gender: "neuter", pronunciation: "le-to", english_example: "Summer is my favorite season.", slovak_example: "Leto je moje obľúbené ročné obdobie." },
      { id: "w-calendar-dat-jesen", english: "autumn", slovak: "jeseň", type: "noun", gender: "feminine", pronunciation: "je-seň", english_example: "Autumn colors are beautiful.", slovak_example: "Jesenné farby sú krásne." },
      { id: "w-calendar-dat-zima", english: "winter", slovak: "zima", type: "noun", gender: "feminine", pronunciation: "zi-ma", english_example: "Winter is cold.", slovak_example: "Zima je studená." },
      { id: "w-calendar-dat-datum", english: "date", slovak: "dátum", type: "noun", gender: "masculine", pronunciation: "dá-tum", english_example: "What's the date today?", slovak_example: "Aký je dnes dátum?" },
      { id: "w-calendar-dat-stredovek", english: "Middle Ages", slovak: "stredovek", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "stre-do-vek", english_example: "The feeling of inferiority is driven to draw on the past to reinforce awareness, especially the Middle Ages, which was without question a Christian dominion, where Christianity gave Europe a face, not only cultural but also religious.", slovak_example: "Pocit menejcennosti pohýna pritiahnuť na posilnenie povedomia minulosť, predovšetkým stredovek, ktorý bol bez diskusie kresťanským panstvom, kde kresťanstvo dalo Európe tvár, nielen kultúrnu, ale aj náboženskú." },
      { id: "w-calendar-dat-hodina", english: "hour", slovak: "hodina", type: "noun", gender: "feminine", pronunciation: "ho-di-na", english_example: "what time is it?", slovak_example: "koľko je hodín?" },
      { id: "w-calendar-dat-mesiac", english: "moon, a satellite of a planet", slovak: "mesiac", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "me-siac", english_example: "Jupiter's moons", slovak_example: "Jupiterove mesiace" },
      { id: "w-calendar-dat-rok", english: "year", slovak: "rok", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "rok", english_example: "New Year's Day", slovak_example: "Nový rok" },
      { id: "w-calendar-dat-potom", english: "after that", slovak: "potom", type: "adverb", pronunciation: "po-tom", english_example: "Go straight, then turn right.", slovak_example: "Choďte rovno, potom sa otočte doprava." },
      { id: "w-calendar-dat-poobede", english: "afternoon", slovak: "poobede", type: "adverb", pronunciation: "po-o-be-de", english_example: "I take a nap in the afternoon.", slovak_example: "Poobede si zdriemnem." },
      { id: "w-calendar-dat-este", english: "again", slovak: "ešte", type: "adverb", pronunciation: "eš-te", english_example: "My package hasn't arrived yet.", slovak_example: "Môj balík ešte neprisiel." },
      { id: "w-calendar-dat-vzdy", english: "always", slovak: "vždy", type: "adverb", pronunciation: "vždy", english_example: "I always drink coffee in the morning.", slovak_example: "Vždy pijem kávu ráno." },
      { id: "w-calendar-dat-kalendar", english: "calendar", slovak: "kalendár", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "ka-len-dár", english_example: "Mark the date in the calendar.", slovak_example: "Označ dátum v kalendári." },
      { id: "w-calendar-dat-storocie", english: "century", slovak: "storočie", type: "noun", gender: "neuter", pronunciation: "sto-ro-čie", english_example: "This building is two centuries old.", slovak_example: "Táto budova je stará dve storočia." },
      { id: "w-calendar-dat-chronologia", english: "chronology", slovak: "chronológia", type: "noun", gender: "feminine", pronunciation: "chro-no-ló-gia", english_example: "Chronology helps us understand history.", slovak_example: "Chronológia nám pomáha pochopiť históriu." },
      { id: "w-calendar-dat-zora", english: "dawn (rising of the sun)", slovak: "zora", type: "noun", gender: "feminine", pronunciation: "zo-ra", english_example: "The dawn breaks over the mountains.", slovak_example: "Zora sa dvíha nad horami." },
      { id: "w-calendar-dat-den", english: "day", slovak: "deň", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "deň", english_example: "What a beautiful day!", slovak_example: "Aký pekný deň!" },
    ],
};
