// AUTO-GENERATED by extract-kaikki-words.py
// Category : Clothing
// Words    : 38 | Examples: 38 | Pronunciation: 38
// Source   : Kaikki_Enriched/*_enriched_categorized/
// Review before merging into src/data/slovak-words.ts

import type { WordCategory } from "@/types/learning";

export const CLOTHING: WordCategory = {
  icon: "👗",
  title: "Clothing",
  description: "Clothes and accessories",
  level: "beginner",
  words: [
      { id: "w-clothing-kosela", english: "shirt", slovak: "košeľa", type: "noun", gender: "feminine", pronunciation: "ko-še-ľa", english_example: "I bought a white shirt.", slovak_example: "Kúpil som bielu košeľu." },
      { id: "w-clothing-tricko", english: "T-shirt", slovak: "tričko", type: "noun", gender: "neuter", pronunciation: "trič-ko", english_example: "I wear a cotton T-shirt.", slovak_example: "Nosím bavlnené tričko." },
      { id: "w-clothing-saty", english: "dress", slovak: "šaty", type: "noun", gender: "feminine", declension_pattern: "žena", synonyms: ["šat"], pronunciation: "ša-ty", english_example: "She wears a red dress.", slovak_example: "Nosí červené šaty." },
      { id: "w-clothing-nohavice", english: "the outer clothing fully or partly covering both legs with two long or short sleeves, trousers", slovak: "nohavice", type: "noun", gender: "feminine", pronunciation: "no-ha-vi-ce", english_example: "These pants are too big.", slovak_example: "Tieto nohavice sú príliš veľké." },
      { id: "w-clothing-dzinsy", english: "jeans", slovak: "džínsy", type: "noun", gender: "feminine", pronunciation: "džín-sy", english_example: "I like blue jeans.", slovak_example: "Mám rád modré džínsy." },
      { id: "w-clothing-sukna", english: "skirt", slovak: "sukňa", type: "noun", gender: "feminine", pronunciation: "suk-ňa", english_example: "She bought a new skirt.", slovak_example: "Kúpila si novú sukňu." },
      { id: "w-clothing-bunda", english: "jacket", slovak: "bunda", type: "noun", gender: "feminine", pronunciation: "bun-da", english_example: "Put on your jacket, it's cold.", slovak_example: "Obleč si bundu, je zima." },
      { id: "w-clothing-plast", english: "coat", slovak: "plášť", type: "noun", gender: "masculine", pronunciation: "plášť", english_example: "My coat is black.", slovak_example: "Môj plášť je čierny." },
      { id: "w-clothing-sveter", english: "sweater; pullover", slovak: "sveter", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "sve-ter", english_example: "I knitted a warm sweater.", slovak_example: "Uplietol som teplý sveter." },
      { id: "w-clothing-ponozky", english: "socks", slovak: "ponožky", type: "noun", gender: "feminine", pronunciation: "po-nož-ky", english_example: "I lost one sock.", slovak_example: "Stratil som jednu ponožku." },
      { id: "w-clothing-topanky", english: "shoes", slovak: "topánky", type: "noun", gender: "feminine", pronunciation: "to-pán-ky", english_example: "These shoes are comfortable.", slovak_example: "Tieto topánky sú pohodlné." },
      { id: "w-clothing-cizmy", english: "boots", slovak: "čižmy", type: "noun", gender: "feminine", pronunciation: "čiž-my", english_example: "Wear boots in winter.", slovak_example: "V zime nos čižmy." },
      { id: "w-clothing-sandale", english: "sandals", slovak: "sandále", type: "noun", gender: "feminine", pronunciation: "san-dá-le", english_example: "I wear sandals in summer.", slovak_example: "V lete nosím sandále." },
      { id: "w-clothing-klobuk", english: "hat", slovak: "klobúk", type: "noun", gender: "masculine", pronunciation: "klo-búk", english_example: "He wears a hat.", slovak_example: "Nosí klobúk." },
      { id: "w-clothing-ciapka", english: "cap", slovak: "čiapka", type: "noun", gender: "feminine", pronunciation: "či-ap-ka", english_example: "I like your cap.", slovak_example: "Páči sa mi tvoja čiapka." },
      { id: "w-clothing-sal", english: "scarf", slovak: "šál", type: "noun", gender: "masculine", pronunciation: "šál", english_example: "She wrapped a scarf around her neck.", slovak_example: "Ovinula si šál okolo krku." },
      { id: "w-clothing-rukavice", english: "gloves", slovak: "rukavice", type: "noun", gender: "feminine", pronunciation: "ru-ka-vi-ce", english_example: "Winter gloves are warm.", slovak_example: "Zimné rukavice sú teplé." },
      { id: "w-clothing-opasok", english: "belt", slovak: "opasok", type: "noun", gender: "masculine", pronunciation: "o-pa-sok", english_example: "He wears a leather belt.", slovak_example: "Nosí kožený opasok." },
      { id: "w-clothing-kravata", english: "necktie", slovak: "kravata", type: "noun", gender: "feminine", synonyms: ["viazanka"], pronunciation: "kra-va-ta", english_example: "He tied his necktie neatly.", slovak_example: "Uviazal si kravatu úhľadne." },
      { id: "w-clothing-velkost", english: "size", slovak: "veľkosť", type: "noun", gender: "feminine", pronunciation: "veľ-kosť", english_example: "What size do you wear?", slovak_example: "Akú veľkosť nosíš?" },
      { id: "w-clothing-ubor", english: "attire, dress, outfit", slovak: "úbor", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "ú-bor", english_example: "business suit", slovak_example: "pracovný úbor" },
      { id: "w-clothing-modraky", english: "working trousers or boiler-suit(s) of blue colour", slovak: "modráky", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "mo-drá-ky", english_example: "one pair of working trousers, one boiler-suit", slovak_example: "jedny modráky" },
      { id: "w-clothing-nohavica", english: "a pant leg", slovak: "nohavica", type: "noun", gender: "feminine", pronunciation: "no-ha-vi-ca", english_example: "The pant leg is torn.", slovak_example: "Nohavica je roztrhnutá." },
      { id: "w-clothing-zastera", english: "apron (clothing)", slovak: "zástera", type: "noun", gender: "feminine", pronunciation: "zás-te-ra", english_example: "She wears an apron while cooking.", slovak_example: "Pri varení nosí zásteru." },
      { id: "w-clothing-hav", english: "attire, robe", slovak: "háv", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "háv", english_example: "The ceremonial robe was beautiful.", slovak_example: "Slávnostný háv bol krásny." },
      { id: "w-clothing-bluza", english: "blouse", slovak: "blúza", type: "noun", gender: "feminine", pronunciation: "blú-za", english_example: "She chose a silk blouse.", slovak_example: "Vybrala si hodvábnu blúzu." },
      { id: "w-clothing-lajblik", english: "bodice", slovak: "lajblík", type: "noun", gender: "masculine", animacy: "inanimate", synonyms: ["živôtik"], pronunciation: "laj-blík", english_example: "The traditional bodice is embroidered.", slovak_example: "Tradičný lajblík je vyšívaný." },
      { id: "w-clothing-oblecenie", english: "clothing", slovak: "oblečenie", type: "noun", gender: "neuter", pronunciation: "ob-le-če-nie", english_example: "Pack warm clothing for the trip.", slovak_example: "Zbaľ si na cestu teplé oblečenie." },
      { id: "w-clothing-huna", english: "coarse fur clothing", slovak: "huňa", type: "noun", gender: "feminine", synonyms: ["širica"], pronunciation: "hu-ňa", english_example: "Shepherds wore huňa in winter.", slovak_example: "Pastieri nosili huňu v zime." },
      { id: "w-clothing-kabat", english: "coat", slovak: "kabát", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "ka-bát", english_example: "His winter coat is very warm.", slovak_example: "Jeho zimný kabát je veľmi teplý." },
      { id: "w-clothing-roba", english: "female evening dress, evening gown", slovak: "róba", type: "noun", gender: "feminine", pronunciation: "ró-ba", english_example: "She wore an elegant evening gown.", slovak_example: "Mala na sebe elegantnú róbu." },
      { id: "w-clothing-jatka", english: "fly (on trousers)", slovak: "jatka", type: "noun", gender: "feminine", pronunciation: "jat-ka", english_example: "Zip up your fly.", slovak_example: "Zapni si jatká." },
      { id: "w-clothing-kozuch", english: "fur coat", slovak: "kožuch", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "ko-žuch", english_example: "The fur coat kept her warm.", slovak_example: "Kožuch ju zahrieval." },
      { id: "w-clothing-rucho", english: "garment", slovak: "rúcho", type: "noun", gender: "neuter", pronunciation: "rú-cho", english_example: "Traditional garments are worn at festivals.", slovak_example: "Tradičné rúcha sa nosia na slávnostiach." },
      { id: "w-clothing-satka", english: "headscarf, scarf", slovak: "šatka", type: "noun", gender: "feminine", declension_pattern: "žena", pronunciation: "šat-ka", english_example: "She tied a scarf around her head.", slovak_example: "Uviazala si šatku okolo hlavy." },
      { id: "w-clothing-vrch", english: "hill (a larger elevation in the terrain)", slovak: "vrch", type: "noun", gender: "masculine", animacy: "inanimate", synonyms: ["breh", "driek", "hromada", "kopa", "kopanice", "kopec", "lazy", "svah"], pronunciation: "vrch", english_example: "We climbed to the top of the hill.", slovak_example: "Vyliezli sme na vrch kopca." },
      { id: "w-clothing-kazajka", english: "jacket", slovak: "kazajka", type: "noun", gender: "feminine", pronunciation: "ka-zaj-ka", english_example: "She wore a traditional jacket.", slovak_example: "Mala na sebe tradičnú kazajku." },
      { id: "w-clothing-dzersej", english: "jersey (article of clothing)", slovak: "džersej", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "džer-sej", english_example: "He wore a sports jersey.", slovak_example: "Mal na sebe športový džersej." },
    ],
};
