// AUTO-GENERATED by extract-kaikki-words.py
// Category : Connectors & Conjunctions
// Words    : 20 | Examples: 20 | Pronunciation: 20
// Source   : Kaikki_Enriched/*_enriched_categorized/
// Review before merging into src/data/slovak-words.ts

import type { WordCategory } from "@/types/learning";

export const CONNECTORS_AND_CONJUNCTIONS: WordCategory = {
  icon: "🔗",
  title: "Connectors & Conjunctions",
  description: "Words that link sentences and express relationships",
  level: "intermediate",
  words: [
      { id: "w-connectors-c-aj", english: "also", slovak: "aj", type: "adverb", pronunciation: "aj", english_example: "I also speak Slovak.", slovak_example: "Hovorím aj po slovensky." },
      { id: "w-connectors-c-hoci", english: "although", slovak: "hoci", type: "expression", pronunciation: "ho-ci", english_example: "Although it rained, we went out.", slovak_example: "Hoci pršalo, išli sme von." },
      { id: "w-connectors-c-lebo", english: "as, since, because", slovak: "lebo", type: "expression", pronunciation: "le-bo", english_example: "He is sad because his dog is sick.", slovak_example: "Je smutný, lebo jeho pes je chorý." },
      { id: "w-connectors-c-pretoze", english: "because", slovak: "pretože", type: "expression", pronunciation: "pre-to-že", english_example: "I'm learning Slovak because I love the culture.", slovak_example: "Učím sa po slovensky, pretože milujem kultúru." },
      { id: "w-connectors-c-ale", english: "but", slovak: "ale", type: "adverb", pronunciation: "a-le", english_example: "I want to go, but I'm tired.", slovak_example: "Chcem ísť, ale som unavený." },
      { id: "w-connectors-c-napriklad", english: "for example, for instance", slovak: "napríklad", type: "adverb", pronunciation: "na-prí-klad", english_example: "I like many fruits, for example apples and bananas.", slovak_example: "Mám rád veľa ovocia, napríklad jablká a banány." },
      { id: "w-connectors-c-jednak", english: "however", slovak: "jednak", type: "adverb", pronunciation: "jed-nak", english_example: "The plan sounds good; however, it needs more details.", slovak_example: "Plán znie dobre; jednak potrebuje viac detailov." },
      { id: "w-connectors-c-avsak", english: "however", slovak: "avšak", type: "adverb", pronunciation: "av-šak", english_example: "I like the idea; however, it's too expensive.", slovak_example: "Páči sa mi nápad; avšak je príliš drahý." },
      { id: "w-connectors-c-ak", english: "if", slovak: "ak", type: "expression", pronunciation: "ak", english_example: "If it rains, we will stay home.", slovak_example: "Ak bude pršať, zostaneme doma." },
      { id: "w-connectors-c-totiz", english: "namely", slovak: "totiž", type: "adverb", pronunciation: "to-tiž", english_example: "I have one favorite city, namely Bratislava.", slovak_example: "Mám jedno obľúbené mesto, totiž Bratislavu." },
      { id: "w-connectors-c-ani", english: "neither", slovak: "ani", type: "expression", pronunciation: "a-ni", english_example: "I don't like coffee, and neither does she.", slovak_example: "Nemám rád kávu a ani ona." },
      { id: "w-connectors-c-len", english: "only, just", slovak: "len", type: "adverb", pronunciation: "len", english_example: "Just a second!", slovak_example: "Len sekundu!" },
      { id: "w-connectors-c-alebo", english: "or", slovak: "alebo", type: "expression", pronunciation: "a-le-bo", english_example: "Is it furnished or unfurnished?", slovak_example: "Je zariadený alebo nezariadený?" },
      { id: "w-connectors-c-cize", english: "that is, i.e.", slovak: "čiže", type: "expression", synonyms: ["teda"], pronunciation: "či-že", english_example: "We need one more thing, that is, your signature.", slovak_example: "Potrebujeme ešte jednu vec, čiže tvoj podpis." },
      { id: "w-connectors-c-preto", english: "therefore, hence", slovak: "preto", type: "adverb", pronunciation: "pre-to", english_example: "He was late; therefore, he missed the meeting.", slovak_example: "Bol neskoro; preto vynechal stretnutie." },
      { id: "w-connectors-c-takze", english: "therefore, so", slovak: "takže", type: "expression", pronunciation: "ta-že", english_example: "It's raining, so we'll stay inside.", slovak_example: "Prší, takže zostaneme vnútri." },
      { id: "w-connectors-c-teda", english: "thus, so", slovak: "teda", type: "expression", pronunciation: "te-da", english_example: "Cogito, ergo sum.", slovak_example: "Myslím, teda som." },
      { id: "w-connectors-c-az", english: "until", slovak: "až", type: "adverb", pronunciation: "až", english_example: "Wait until tomorrow.", slovak_example: "Počkaj až do zajtra." },
      { id: "w-connectors-c-ked", english: "when", slovak: "keď", type: "expression", pronunciation: "keď", english_example: "I lie down when I'm tired.", slovak_example: "Ľahnem si, keď som unavený." },
      { id: "w-connectors-c-pricom", english: "whereas, while", slovak: "pričom", type: "expression", pronunciation: "pri-čom", english_example: "He likes coffee, whereas she prefers tea.", slovak_example: "On má rád kávu, pričom ona preferuje čaj." },
    ],
};
