// AUTO-GENERATED by extract-kaikki-words.py
// Category : Family
// Words    : 38 | Examples: 0 | IPA: 38
// Source   : Kaikki_Enriched/*_enriched_categorized/
// Review before merging into src/data/slovak-words.ts

import type { WordCategory } from "@/types/learning";

export const FAMILY: WordCategory = {
  icon: "👨‍👩‍👧",
  title: "Family",
  description: "Family members and relationships",
  level: "beginner",
  words: [
      { id: "w-family-mama", english: "mama", slovak: "mama", type: "noun", gender: "feminine", declension_pattern: "žena", pronunciation: "/mama/", english_example: "My mother cooks well.", slovak_example: "Moja mama dobre varí." },
      { id: "w-family-otec", english: "father", slovak: "otec", type: "noun", gender: "masculine", pronunciation: "/ɔcet͡s/", english_example: "My father reads the newspaper.", slovak_example: "Môj otec číta noviny." },
      { id: "w-family-brat", english: "brother", slovak: "brat", type: "noun", gender: "masculine", pronunciation: "/brat/", english_example: "He lives in Bratislava.", slovak_example: "On býva v Bratislave." },
      { id: "w-family-sestra", english: "sister (a female sibling)", slovak: "sestra", type: "noun", gender: "feminine", pronunciation: "/sestra/", english_example: "She is my sister.", slovak_example: "Ona je moja sestra." },
      { id: "w-family-dieta", english: "child", slovak: "dieťa", type: "noun", gender: "neuter", pronunciation: "/ɟɪ̯eca/", english_example: "I have two children.", slovak_example: "Mám dve deti." },
      { id: "w-family-syn", english: "son (male offspring)", slovak: "syn", type: "noun", gender: "masculine", pronunciation: "/sin/", english_example: "My son goes to school.", slovak_example: "Môj syn chodí do školy." },
      { id: "w-family-dcera", english: "daughter (female offspring)", slovak: "dcéra", type: "noun", gender: "feminine", pronunciation: "/t͡seːra/", english_example: "My daughter drinks milk.", slovak_example: "Moja dcéra pije mlieko." },
      { id: "w-family-dedko", english: "grandfather", slovak: "dedko", type: "noun", gender: "masculine", pronunciation: "/ɟetkɔ/" },
      { id: "w-family-babicka", english: "grandmother", slovak: "babička", type: "noun", gender: "feminine", pronunciation: "/babit͡ʃka/", synonyms: ["babka", "starenka", "starká"] },
      { id: "w-family-vnuk", english: "grandson", slovak: "vnuk", type: "noun", gender: "masculine", pronunciation: "/vnuk/" },
      { id: "w-family-vnucka", english: "granddaughter", slovak: "vnučka", type: "noun", gender: "feminine", pronunciation: "/vnut͡ʃka/" },
      { id: "w-family-ujo", english: "maternal uncle", slovak: "ujo", type: "noun", gender: "masculine", pronunciation: "/ujɔ/", synonyms: ["ujec"] },
      { id: "w-family-stryko", english: "paternal uncle", slovak: "strýko", type: "noun", gender: "masculine", pronunciation: "/striːkɔ/" },
      { id: "w-family-teta", english: "aunt (a parent's sister)", slovak: "teta", type: "noun", gender: "feminine", pronunciation: "/ceta/" },
      { id: "w-family-bratranec", english: "cousin", slovak: "bratranec", type: "noun", gender: "masculine", pronunciation: "/bratraɲet͡s/" },
      { id: "w-family-manzel", english: "husband", slovak: "manžel", type: "noun", gender: "masculine", pronunciation: "/manʒel/", synonyms: ["muž"] },
      { id: "w-family-manzelka", english: "wife", slovak: "manželka", type: "noun", gender: "feminine", pronunciation: "/manʒelka/", synonyms: ["žena"] },
      { id: "w-family-priatel", english: "friend", slovak: "priateľ", type: "noun", gender: "masculine", animacy: "animate", pronunciation: "/priaceʎ/", english_example: "He is my best friend.", slovak_example: "Je to môj najlepší priateľ." },
      { id: "w-family-rodina", english: "family", slovak: "rodina", type: "noun", gender: "feminine", pronunciation: "/rɔɟina/", english_example: "My family lives in Žilina.", slovak_example: "Moja rodina býva v Žiline." },
      { id: "w-family-zat", english: "son-in-law (daughter's husband)", slovak: "zať", type: "noun", gender: "masculine", pronunciation: "/zac/", english_example: "Can you substantiate your claim?", slovak_example: "Vieš dokázať svoje tvrdenie?" },
      { id: "w-family-snacha", english: "daughter-in-law", slovak: "snacha", type: "noun", gender: "feminine", pronunciation: "/snaxa/" },
      { id: "w-family-svak", english: "brother-in-law", slovak: "svák", type: "noun", gender: "masculine", pronunciation: "/svaːk/" },
      { id: "w-family-svokor", english: "father-in-law (husband's father)", slovak: "svokor", type: "noun", gender: "masculine", pronunciation: "/svɔkɔr/", synonyms: ["tesť"] },
      { id: "w-family-test", english: "father-in-law (wife's father)", slovak: "tesť", type: "noun", gender: "masculine", pronunciation: "/cesc/" },
      { id: "w-family-rodopis", english: "genealogy", slovak: "rodopis", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "/rɔdɔpis/", synonyms: ["genealógia"] },
      { id: "w-family-praded", english: "great-grandfather", slovak: "praded", type: "noun", gender: "masculine", pronunciation: "/praɟet/", synonyms: ["pradedo"] },
      { id: "w-family-pradedo", english: "great-grandfather", slovak: "pradedo", type: "noun", gender: "masculine", pronunciation: "/praɟedɔ/", synonyms: ["praded"] },
      { id: "w-family-prababa", english: "great-grandmother", slovak: "prababa", type: "noun", gender: "feminine", pronunciation: "/prababa/" },
      { id: "w-family-prababicka", english: "great-grandmother", slovak: "prababička", type: "noun", gender: "feminine", pronunciation: "/prababit͡ʃka/", synonyms: ["prababa"] },
      { id: "w-family-muz", english: "man (an adult male human)", slovak: "muž", type: "noun", gender: "masculine", pronunciation: "/muʃ/", english_example: "The man is reading a book.", slovak_example: "Muž číta knihu." },
      { id: "w-family-ujec", english: "maternal uncle", slovak: "ujec", type: "noun", gender: "masculine", pronunciation: "/ujet͡s/", synonyms: ["ujo"] },
      { id: "w-family-matka", english: "mother", slovak: "matka", type: "noun", gender: "feminine", pronunciation: "/matka/", synonyms: ["mama", "mamička", "mater", "mať"] },
      { id: "w-family-roditelka", english: "mother", slovak: "roditeľka", type: "noun", gender: "feminine", pronunciation: "/rɔɟiceʎka/" },
      { id: "w-family-svokra", english: "mother-in-law (husband's mother)", slovak: "svokra", type: "noun", gender: "feminine", pronunciation: "/svɔkra/", synonyms: ["testiná"] },
      { id: "w-family-dedo", english: "old man", slovak: "dedo", type: "noun", gender: "masculine", pronunciation: "/ɟedɔ/", synonyms: ["ded", "starec", "starý otec"] },
      { id: "w-family-sirota", english: "orphan (someone whose parents have died)", slovak: "sirota", type: "noun", gender: "feminine", pronunciation: "/sirɔta/" },
      { id: "w-family-stryna", english: "paternal aunt-by-marriage; the wife of a strýc", slovak: "stryná", type: "noun", gender: "feminine", pronunciation: "/strinaː/" },
      { id: "w-family-stryc", english: "paternal uncle", slovak: "strýc", type: "noun", gender: "masculine", pronunciation: "/striːt͡s/" },
      { id: "w-family-zolvica", english: "sister-in-law", slovak: "zolvica", type: "noun", gender: "feminine", declension_pattern: "ulica", pronunciation: "/zɔlvit͡sa/", synonyms: ["švagriná"] },
      { id: "w-family-zena", english: "woman", slovak: "žena", type: "noun", gender: "feminine", pronunciation: "/ʒena/" }
    ],
};