// AUTO-GENERATED by extract-kaikki-words.py
// Category : Law & Administration
// Words    : 27 | Examples: 27 | Pronunciation: 27
// Source   : Kaikki_Enriched/*_enriched_categorized/
// Review before merging into src/data/slovak-words.ts

import type { WordCategory } from "@/types/learning";

export const POLICE_AND_AUTHORITIES: WordCategory = {
  icon: "⚖️",
  title: "Law & Administration",
  description: "Legal and administrative vocabulary",
  level: "advanced",
  words: [
      { id: "w-police-autho-policia", english: "police", slovak: "polícia", type: "noun", gender: "feminine", pronunciation: "po-lí-cia", english_example: "Call the police!", slovak_example: "Zavolajte políciu!" },
      { id: "w-police-autho-policajt", english: "officer", slovak: "policajt", type: "noun", gender: "masculine", pronunciation: "po-li-cajt", english_example: "The officer helped me.", slovak_example: "Policajt mi pomohol." },
      { id: "w-police-autho-pas", english: "passport", slovak: "pas", type: "noun", gender: "masculine", pronunciation: "pas", english_example: "I lost my passport.", slovak_example: "Stratil som pas." },
      { id: "w-police-autho-obciansky-preukaz", english: "ID card", slovak: "občiansky preukaz", type: "noun", gender: "masculine", pronunciation: "ob-čian-sky preu-kaz", english_example: "Show your ID card.", slovak_example: "Ukážte svoj občiansky preukaz." },
      { id: "w-police-autho-povolenie-na-pobyt", english: "residence permit", slovak: "povolenie na pobyt", type: "noun", gender: "neuter", pronunciation: "po-vo-le-nie na po-byt", english_example: "My residence permit expires soon.", slovak_example: "Moje povolenie na pobyt čoskoro vyprší." },
      { id: "w-police-autho-hlasenie", english: "report", slovak: "hlásenie", type: "noun", gender: "neuter", pronunciation: "hlá-se-nie", english_example: "I filed a police report.", slovak_example: "Podal som policajné hlásenie." },
      { id: "w-police-autho-kradez", english: "theft", slovak: "krádež", type: "noun", gender: "feminine", pronunciation: "krá-dež", english_example: "There was a theft last night.", slovak_example: "Minulú noc bola krádež." },
      { id: "w-police-autho-nehoda", english: "accident", slovak: "nehoda", type: "noun", gender: "feminine", pronunciation: "ne-ho-da", english_example: "I witnessed a car accident.", slovak_example: "Bol som svedkom autonehody." },
      { id: "w-police-autho-nudzova-situacia", english: "emergency", slovak: "núdzová situácia", type: "noun", gender: "feminine", pronunciation: "núd-zo-vá si-tu-á-cia", english_example: "In case of emergency, call 112.", slovak_example: "V prípade núdzovej situácie volajte 112." },
      { id: "w-police-autho-pokuta", english: "fine", slovak: "pokuta", type: "noun", gender: "feminine", pronunciation: "po-ku-ta", english_example: "I got a parking fine.", slovak_example: "Dostal som pokutu za parkovanie." },
      { id: "w-police-autho-svedok", english: "witness", slovak: "svedok", type: "noun", gender: "masculine", pronunciation: "sve-dok", english_example: "He is a key witness.", slovak_example: "Je kľúčovým svedkom." },
      { id: "w-police-autho-nahlasit", english: "to report", slovak: "nahlásiť", type: "verb", pronunciation: "nah-lá-siť", english_example: "I need to report a crime.", slovak_example: "Potrebujem nahlásiť trestný čin." },
      { id: "w-police-autho-stratit", english: "to lose", slovak: "stratiť", type: "verb", pronunciation: "stra-tiť", english_example: "I lost my wallet.", slovak_example: "Stratil som peňaženku." },
      { id: "w-police-autho-ukradnut", english: "to steal", slovak: "ukradnúť", type: "verb", pronunciation: "uk-rad-núť", english_example: "Someone stole my bike.", slovak_example: "Niekto mi ukradol bicykel." },
      { id: "w-police-autho-pomoct", english: "to help", slovak: "pomôcť", type: "verb", pronunciation: "po-môcť", english_example: "Can you help me?", slovak_example: "Môžete mi pomôcť?" },
      { id: "w-police-autho-cudzinecka-policia", english: "foreign police", slovak: "cudzinecká polícia", type: "noun", gender: "feminine", pronunciation: "cu-dzi-nec-ká po-lí-cia", english_example: "I went to the foreign police.", slovak_example: "Išiel som na cudzineckú políciu." },
      { id: "w-police-autho-dokument", english: "document", slovak: "dokument", type: "noun", gender: "masculine", pronunciation: "do-ku-ment", english_example: "Bring all your documents.", slovak_example: "Prines všetky svoje dokumenty." },
      { id: "w-police-autho-preklad", english: "translation", slovak: "preklad", type: "noun", gender: "masculine", pronunciation: "pre-klad", english_example: "I need an official translation.", slovak_example: "Potrebujem úradný preklad." },
      { id: "w-police-autho-overeny", english: "certified", slovak: "overený", type: "adjective", pronunciation: "o-ve-re-ný", english_example: "The translation must be certified.", slovak_example: "Preklad musí byť overený." },
      { id: "w-police-autho-petit", english: "grade font size of 8 points (3,009 mm)", slovak: "petit", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "pe-tit", english_example: "Parts in the dictionary are printed with petit.", slovak_example: "Časti v slovníku sú vytlačené petitom." },
      { id: "w-police-autho-zmenka", english: "promissory note, bill of exchange", slovak: "zmenka", type: "noun", gender: "feminine", pronunciation: "zmen-ka", english_example: "The creditor accepted the promissory note instead of an immediate cash payment.", slovak_example: "Veriteľ prijal zmenku namiesto okamžitej hotovostnej platby." },
      { id: "w-police-autho-obstavka", english: "sequestration, distraint, attachment", slovak: "obstávka", type: "noun", gender: "feminine", synonyms: ["obstavenie"], pronunciation: "ob-stáv-ka", english_example: "Indebted hospitals face a real threat of property sequestration, which could paralyze their operation.", slovak_example: "Zadlženým nemocniciam reálne hrozí obstávka majetku, čo by mohlo ochromiť ich prevádzku." },
      { id: "w-police-autho-obstavit", english: "to place around, to surround with", slovak: "obstaviť", type: "verb", aspect: "perfective", aspect_pair: "obstavovať", synonyms: ["obklopiť", "obkolesiť", "obstavať", "zablokovať", "zadržať", "zastaviť"], pronunciation: "ob-sta-viť", english_example: "The room was lined all around with massive wooden cabinets.", slovak_example: "Izba bola po celom obvode obstavená masívnymi drevenými skriňami." },
      { id: "w-police-autho-legislatura", english: "legislature", slovak: "legislatúra", type: "noun", gender: "feminine", pronunciation: "le-gis-la-tú-ra", english_example: "The legislature passes new laws.", slovak_example: "Legislatúra schvaľuje nové zákony." },
      { id: "w-police-autho-mediacia", english: "mediation", slovak: "mediácia", type: "noun", gender: "feminine", pronunciation: "me-diá-cia", english_example: "Mediation helped resolve the dispute.", slovak_example: "Mediácia pomohla vyriešiť spor." },
      { id: "w-police-autho-milost", english: "mercy", slovak: "milosť", type: "noun", gender: "feminine", pronunciation: "mi-losť", english_example: "The prisoner begged for mercy.", slovak_example: "Väzeň prosil o milosť." },
      { id: "w-police-autho-faraon", english: "pharaoh", slovak: "faraón", type: "noun", gender: "masculine", pronunciation: "fa-ra-ón", english_example: "The pharaoh ruled ancient Egypt.", slovak_example: "Faraón vládol starovekému Egyptu." },
    ],
};
