// AUTO-GENERATED by extract-kaikki-words.py
// Category : Transport
// Words    : 22 | Examples: 8 | IPA: 22
// Source   : Kaikki_Enriched/*_enriched_categorized/
// Review before merging into src/data/slovak-words.ts

import type { WordCategory } from "@/types/learning";

export const TRANSPORT: WordCategory = {
  icon: "🚌",
  title: "Transport",
  description: "Vehicles and getting around",
  level: "beginner",
  words: [
      { id: "w-transport-auto", english: "car", slovak: "auto", type: "noun", gender: "neuter", pronunciation: "/autɔ/", english_example: "I go to work by car.", slovak_example: "Do práce chodím autom." },
      { id: "w-transport-vlak", english: "train (line of connected cars or carriages)", slovak: "vlak", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "/vlak/", english_example: "I take the train to Brno.", slovak_example: "Idem vlakom do Brna." },
      { id: "w-transport-autobus", english: "bus", slovak: "autobus", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "/autɔbus/", english_example: "Which bus goes to the centre?", slovak_example: "Ktorý autobus ide do centra?" },
      { id: "w-transport-elektricka", english: "tram, trolley, streetcar", slovak: "električka", type: "noun", gender: "feminine", pronunciation: "/elektrit͡ʃka/" },
      { id: "w-transport-bicykel", english: "bicycle", slovak: "bicykel", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "/bit͡sikel/" },
      { id: "w-transport-taxik", english: "taxi", slovak: "taxík", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "/taksiːk/", english_example: "Can I get a taxi, please?", slovak_example: "Môžem dostať taxík, prosím?" },
      { id: "w-transport-stanica", english: "station", slovak: "stanica", type: "noun", gender: "feminine", pronunciation: "/staɲit͡sa/", english_example: "The station is nearby.", slovak_example: "Stanica je blízko." },
      { id: "w-transport-nadrazie", english: "railway station", slovak: "nádražie", type: "noun", gender: "neuter", pronunciation: "/naːdraʒɪ̯e/", synonyms: ["železničná stanica"], english_example: "New and new problems were increasing enormously. Spatial, transport, traffic, park, housing and health problems had to be solved. Objects with completely new purposes emerged to solve them, such as factories, markets, power plants and railway stations.", slovak_example: "Nových a nových problémov enormne pribúdalo. Bolo treba riešiť priestorové, dopravné, premávkové, parkové, bytové a zdravotné problémy. Vynárali sa na riešenie objekty celkom nového určenia, ako továrne, tržnice, elektrárne, nádražia." },
      { id: "w-transport-letisko", english: "airport", slovak: "letisko", type: "noun", gender: "neuter", pronunciation: "/ʎeciskɔ/", english_example: "The airport is outside the city.", slovak_example: "Letisko je mimo mesta." },
      { id: "w-transport-zastavka", english: "stop, halt, pause", slovak: "zastávka", type: "noun", gender: "feminine", pronunciation: "/zastaːvka/", synonyms: ["prerušenie", "prestávka", "stanica", "zastavenie", "úsek"], english_example: "After three hours of a demanding climb, we made a short stop at a mountain spring.", slovak_example: "Po troch hodinách náročného výstupu sme si urobili krátku zastávku pri horskom prameni." },
      { id: "w-transport-ulica", english: "street", slovak: "ulica", type: "noun", gender: "feminine", pronunciation: "/uʎit͡sa/", english_example: "Which street is it on?", slovak_example: "Na ktorej ulici to je?" },
      { id: "w-transport-cesta", english: "road / way", slovak: "cesta", type: "noun", gender: "feminine", pronunciation: "/t͡sesta/", english_example: "How much will it cost to get to the city center?", slovak_example: "Koľko bude stáť cesta do centra mesta?" },
      { id: "w-transport-listok", english: "ticket", slovak: "lístok", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "/liːstɔk/", english_example: "Where can I buy a ticket?", slovak_example: "Kde si môžem kúpiť lístok?" },
      { id: "w-transport-miestenka", english: "seat reservation ticket", slovak: "miestenka", type: "noun", gender: "feminine", pronunciation: "/mɪ̯escenka/" },
      { id: "w-transport-elektricenka", english: "travel card", slovak: "električenka", type: "noun", gender: "feminine", pronunciation: "/elektrit͡ʃenka/" },
      { id: "w-transport-nastupiste", english: "platform", slovak: "nástupište", type: "noun", gender: "neuter", pronunciation: "/naːstupisʃce/" },
      { id: "w-transport-meskanie", english: "delay", slovak: "meškanie", type: "noun", gender: "neuter", pronunciation: "/meskaɲɪ̯e/" },
      { id: "w-transport-cestovat", english: "to travel", slovak: "cestovať", type: "verb", aspect: "imperfective", pronunciation: "/t͡sestɔvac/" },
      { id: "w-transport-nastupit", english: "to get on", slovak: "nastúpiť", type: "verb", aspect: "perfective", aspect_pair: "nastupovať", pronunciation: "/nastupic/" },
      { id: "w-transport-vystupit", english: "to get off", slovak: "vystúpiť", type: "verb", aspect: "perfective", aspect_pair: "vystupovať", pronunciation: "/vistupic/" },
      { id: "w-transport-prestupit", english: "to change (transport)", slovak: "prestúpiť", type: "verb", aspect: "perfective", aspect_pair: "prestupovať", pronunciation: "/prestupic/" },
      { id: "w-transport-vymena", english: "replacement, exchange, substitution", slovak: "výmena", type: "noun", gender: "feminine", pronunciation: "/viːmena/", synonyms: ["nahradenie", "vymenenie"], english_example: "The complaint was resolved by an immediate exchange of goods.", slovak_example: "Reklamácia bola vybavená okamžitou výmenou tovaru." },
      { id: "w-transport-stojisko", english: "stall", slovak: "stojisko", type: "noun", gender: "neuter", pronunciation: "/stɔjiskɔ/", synonyms: ["odstavná plocha", "parkovacie miesto"], english_example: "Each dairy cow in the barn has its own stall.", slovak_example: "Každá dojnica v maštali má svoje vlastné stojisko." },
      { id: "w-transport-prezut", english: "to change", slovak: "prezuť", type: "verb", aspect: "perfective", aspect_pair: "prezúvať", pronunciation: "/prezuc/", synonyms: ["preobuť"], english_example: "Before entering the kindergarten, she had to quickly change the child into slippers.", slovak_example: "Pred vstupom do škôlky musela rýchlo prezuť dieťa do papúč." },
      { id: "w-transport-obut", english: "to put on", slovak: "obuť", type: "verb", aspect: "perfective", aspect_pair: "obúvať", pronunciation: "/ɔbuc/", synonyms: ["kritizovať", "pustiť", "zaobuť", "zaútočiť", "začať"], english_example: "The mother helped the child put on roller skates.", slovak_example: "Mama pomohla dieťaťu obuť kolieskové korčule." },
      { id: "w-transport-odstavit", english: "to shut down, to take out of service", slovak: "odstaviť", type: "verb", aspect: "perfective", aspect_pair: "odstavovať", pronunciation: "/ɔt͡stavic/", synonyms: ["odložiť", "odlúčiť", "odparkovať", "odtiahnuť", "uzavrieť", "vyradiť", "zastaviť"], english_example: "Due to a general overhaul, they had to shut down the entire production line at the car factory for a month.", slovak_example: "Z dôvodu generálnej opravy museli na mesiac odstaviť celý výrobný pás v automobilke." },
      { id: "w-transport-cestovatel", english: "traveller", slovak: "cestovateľ", type: "noun", gender: "masculine", pronunciation: "/t͡sestɔvaceʎ/", english_example: "They were also \"discovered\" by independent travellers, often foreigners.", slovak_example: "Tiež ich „objavili\" nezávislí cestovatelia, často cudzinci." },
      { id: "w-transport-rusen", english: "engine, locomotive", slovak: "rušeň", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "/ruʃeɲ/", synonyms: ["lokomotíva"] },
      { id: "w-transport-lokomotiva", english: "engine, locomotive", slovak: "lokomotíva", type: "noun", gender: "feminine", pronunciation: "/lɔkɔmɔtiːva/", synonyms: ["rušeň"] },
      { id: "w-transport-brod", english: "ford, crossing, location where a stream is shallow", slovak: "brod", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "/brɔt/" },
      { id: "w-transport-put", english: "journey, travel, wandering", slovak: "púť", type: "noun", gender: "feminine", pronunciation: "/puːc/", synonyms: ["cesta", "cestovanie", "putovanie"] },
      { id: "w-transport-mikrobus", english: "minibus", slovak: "mikrobus", type: "noun", gender: "masculine", animacy: "inanimate", declension_pattern: "dub", pronunciation: "/ˈmikrɔbus/" },
      { id: "w-transport-zeleznica", english: "railroad, railway", slovak: "železnica", type: "noun", gender: "feminine", pronunciation: "/ʒeʎezɲit͡sa/", synonyms: ["koľaj"] },
      { id: "w-transport-kolaj", english: "rut, track, groove", slovak: "koľaj", type: "noun", gender: "feminine", pronunciation: "/kɔʎaj/" },
      { id: "w-transport-spojler", english: "spoiler", slovak: "spojler", type: "noun", gender: "masculine", animacy: "inanimate", pronunciation: "/spɔjler/" },
      { id: "w-transport-draha", english: "track (for a race or exercise)", slovak: "dráha", type: "noun", gender: "feminine", pronunciation: "/draːɦa/", synonyms: ["trajektória", "železnica"] },
      { id: "w-transport-koleso", english: "wheel", slovak: "koleso", type: "noun", gender: "neuter", pronunciation: "/kɔʎesɔ/" }
    ],
};